// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Enhanced error handling for environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL) {
  console.error('Missing VITE_SUPABASE_URL environment variable');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Enhanced Supabase client with better error handling
export const supabase = createClient<Database>(
  SUPABASE_URL || 'http://localhost:54321', 
  SUPABASE_PUBLISHABLE_KEY || 'missing-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    global: {
      // Add timeout and retry configuration
      fetch: (input, init) => {
        // Add timeout to fetch requests
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 10000); // 10 second timeout
        
        return fetch(input, {
          ...init,
          signal: controller.signal
        }).finally(() => {
          clearTimeout(timeoutId);
        });
      }
    },
    db: {
      schema: 'public',
    }
  }
);

// Add a health check function
export const checkSupabaseHealth = async () => {
  try {
    // Simple query to check connectivity
    const { data, error } = await supabase
      .from('profiles')
      .select('id')
      .limit(1)
      .maybeSingle();
    
    if (error) {
      console.error('Supabase health check failed:', error);
      return { healthy: false, error: error.message };
    }
    
    return { healthy: true, error: null };
  } catch (err) {
    console.error('Supabase health check error:', err);
    return { healthy: false, error: err instanceof Error ? err.message : 'Unknown error' };
  }
};